/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package T_Pregunta;

/**
 *
 * @author Usuario
 */
public class NuevaPregunta2 extends javax.swing.JPanel {

    /**
     * Creates new form NuevaPregunta
     */
    public NuevaPregunta2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPregunta = new javax.swing.JPanel();
        txtTituloPregunta = new javax.swing.JTextField();
        rbCerrada = new javax.swing.JRadioButton();
        rbAbierta = new javax.swing.JRadioButton();
        lbTipo = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(910, 100));
        setMinimumSize(new java.awt.Dimension(910, 100));
        setPreferredSize(new java.awt.Dimension(910, 100));

        pnlPregunta.setBackground(new java.awt.Color(193, 224, 255));
        pnlPregunta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlPregunta.setMaximumSize(new java.awt.Dimension(910, 100));
        pnlPregunta.setMinimumSize(new java.awt.Dimension(910, 100));
        pnlPregunta.setPreferredSize(new java.awt.Dimension(910, 100));

        txtTituloPregunta.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        txtTituloPregunta.setText("Pregunta sin titulo");

        rbCerrada.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        rbCerrada.setText("Cerrada");

        rbAbierta.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        rbAbierta.setText("Abierta");

        lbTipo.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        lbTipo.setText("Tipo :");

        javax.swing.GroupLayout pnlPreguntaLayout = new javax.swing.GroupLayout(pnlPregunta);
        pnlPregunta.setLayout(pnlPreguntaLayout);
        pnlPreguntaLayout.setHorizontalGroup(
            pnlPreguntaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPreguntaLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(pnlPreguntaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTituloPregunta, javax.swing.GroupLayout.PREFERRED_SIZE, 830, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlPreguntaLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lbTipo)
                        .addGap(18, 18, 18)
                        .addComponent(rbCerrada)
                        .addGap(18, 18, 18)
                        .addComponent(rbAbierta)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        pnlPreguntaLayout.setVerticalGroup(
            pnlPreguntaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPreguntaLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(txtTituloPregunta, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(pnlPreguntaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTipo)
                    .addComponent(rbCerrada)
                    .addComponent(rbAbierta))
                .addGap(11, 11, 11))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 910, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlPregunta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(pnlPregunta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbTipo;
    private javax.swing.JPanel pnlPregunta;
    private javax.swing.JRadioButton rbAbierta;
    private javax.swing.JRadioButton rbCerrada;
    private javax.swing.JTextField txtTituloPregunta;
    // End of variables declaration//GEN-END:variables
}
