
package Aplicacion;

import java.awt.BorderLayout;
import java.time.LocalDate;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import javax.swing.Timer;


/**
 *
 * @author user
 */
public class MenuParticipante extends javax.swing.JFrame {

    /**
     * Creates new form MenuOpciones_Encuestador
     */
    public MenuParticipante() {
        initComponents();
        mensajeFecha();
        mensajeHora();
        this.setTitle("JDM Surveys - MenuOpciones");
        this.setSize(940, 580);
        this.setLocationRelativeTo(null);
    }
    
    public void mensajeFecha(){
        //Importamos la libreria LocalDate
        LocalDate nuevoDate = LocalDate.now();
        
        //creacion de Variables
        int año;
        int dia;
        int mes;
        
        año = nuevoDate.getYear();
        dia = nuevoDate.getDayOfMonth();
        mes = nuevoDate.getMonthValue();
        
        //Definimos un Arreglo
        String[] meses= {"01","02","03","04","05","06","07","08","09","10","11","12"};
        lbFecha.setText(dia+"/"+meses[mes-1]+"/"+año);
    }

    public void mensajeHora(){
      Calendar nuevocalendario = new GregorianCalendar();  // Crear el calendario
        Date horaActual = new Date();                   // Obtener la fecha y hora actual
            nuevocalendario.setTime(horaActual);        // Configurar el calendario con la hora actual
            
        //Crear las variables
        String hora;
        String minutos;
        String horaCompleta;
 
        // Obtener la hora y formatearla con ceros si es necesario
        hora = nuevocalendario.get(Calendar.HOUR_OF_DAY) > 9 
                        ? "" + nuevocalendario.get(Calendar.HOUR_OF_DAY) 
                        : "0" + nuevocalendario.get(Calendar.HOUR_OF_DAY);

        // Obtener los minutos y formatearlos con ceros si es necesario
        minutos = nuevocalendario.get(Calendar.MINUTE) > 9 
                        ? "" + nuevocalendario.get(Calendar.MINUTE) 
                        : "0" + nuevocalendario.get(Calendar.MINUTE);

        // Unir la hora, los minutos y los segundos en un formato "HH:mm:ss"
        horaCompleta = hora + ":" + minutos;

        // Asignar la hora formateada al Label
        jlHora.setText(horaCompleta);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FondoBlanco = new javax.swing.JPanel();
        MenuOpciones = new javax.swing.JPanel();
        Icon = new javax.swing.JLabel();
        btnInicio = new javax.swing.JButton();
        btnEncuestasRecibidas = new javax.swing.JButton();
        btnEncuestasRespondidas = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        Contorno = new javax.swing.JPanel();
        Fecha = new javax.swing.JPanel();
        lbFecha = new javax.swing.JLabel();
        jlHora = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 500));

        FondoBlanco.setBackground(new java.awt.Color(255, 204, 102));
        FondoBlanco.setPreferredSize(new java.awt.Dimension(800, 500));

        MenuOpciones.setBackground(new java.awt.Color(255, 255, 204));

        Icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Logo JDM Surveys (JPEG) (140px) (Fondo 0).png"))); // NOI18N

        btnInicio.setBackground(new java.awt.Color(255, 204, 102));
        btnInicio.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        btnInicio.setForeground(new java.awt.Color(0, 0, 0));
        btnInicio.setText("Inicio");
        btnInicio.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        btnInicio.setBorderPainted(false);
        btnInicio.setContentAreaFilled(false);
        btnInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInicio.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnInicio.setIconTextGap(10);
        btnInicio.setOpaque(true);
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });

        btnEncuestasRecibidas.setBackground(new java.awt.Color(255, 204, 102));
        btnEncuestasRecibidas.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        btnEncuestasRecibidas.setForeground(new java.awt.Color(0, 0, 0));
        btnEncuestasRecibidas.setText("Encuestas Recibidas");
        btnEncuestasRecibidas.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        btnEncuestasRecibidas.setBorderPainted(false);
        btnEncuestasRecibidas.setContentAreaFilled(false);
        btnEncuestasRecibidas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEncuestasRecibidas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnEncuestasRecibidas.setIconTextGap(10);
        btnEncuestasRecibidas.setOpaque(true);
        btnEncuestasRecibidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEncuestasRecibidasActionPerformed(evt);
            }
        });

        btnEncuestasRespondidas.setBackground(new java.awt.Color(255, 204, 102));
        btnEncuestasRespondidas.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        btnEncuestasRespondidas.setForeground(new java.awt.Color(0, 0, 0));
        btnEncuestasRespondidas.setText("Encuestas Respondidas");
        btnEncuestasRespondidas.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        btnEncuestasRespondidas.setBorderPainted(false);
        btnEncuestasRespondidas.setContentAreaFilled(false);
        btnEncuestasRespondidas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEncuestasRespondidas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnEncuestasRespondidas.setIconTextGap(10);
        btnEncuestasRespondidas.setOpaque(true);

        btnSalir.setBackground(new java.awt.Color(255, 204, 102));
        btnSalir.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(0, 0, 0));
        btnSalir.setText("Salir");
        btnSalir.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        btnSalir.setBorderPainted(false);
        btnSalir.setContentAreaFilled(false);
        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnSalir.setIconTextGap(10);
        btnSalir.setOpaque(true);

        jLabel4.setFont(new java.awt.Font("Cabin Sketch", 2, 48)); // NOI18N
        jLabel4.setText("JDM ");

        javax.swing.GroupLayout MenuOpcionesLayout = new javax.swing.GroupLayout(MenuOpciones);
        MenuOpciones.setLayout(MenuOpcionesLayout);
        MenuOpcionesLayout.setHorizontalGroup(
            MenuOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuOpcionesLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(Icon, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(43, 43, 43))
            .addGroup(MenuOpcionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(MenuOpcionesLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(MenuOpcionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnEncuestasRecibidas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(MenuOpcionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnEncuestasRespondidas, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(MenuOpcionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        MenuOpcionesLayout.setVerticalGroup(
            MenuOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuOpcionesLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(Icon, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnInicio, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEncuestasRecibidas, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEncuestasRespondidas, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                .addGap(108, 108, 108)
                .addComponent(btnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                .addGap(34, 34, 34))
        );

        Contorno.setBackground(new java.awt.Color(255, 255, 153));
        Contorno.setMaximumSize(new java.awt.Dimension(400, 400));
        Contorno.setMinimumSize(new java.awt.Dimension(400, 400));
        Contorno.setPreferredSize(new java.awt.Dimension(550, 450));

        javax.swing.GroupLayout ContornoLayout = new javax.swing.GroupLayout(Contorno);
        Contorno.setLayout(ContornoLayout);
        ContornoLayout.setHorizontalGroup(
            ContornoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        ContornoLayout.setVerticalGroup(
            ContornoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        Fecha.setBackground(new java.awt.Color(255, 204, 204));

        lbFecha.setFont(new java.awt.Font("Myanmar Text", 1, 12)); // NOI18N
        lbFecha.setForeground(new java.awt.Color(0, 0, 0));
        lbFecha.setText("{day}/{month}/{year}");

        jlHora.setBackground(new java.awt.Color(0, 0, 0));
        jlHora.setFont(new java.awt.Font("Myanmar Text", 1, 12)); // NOI18N
        jlHora.setForeground(new java.awt.Color(0, 0, 0));
        jlHora.setText("{HH}:{mm}");

        javax.swing.GroupLayout FechaLayout = new javax.swing.GroupLayout(Fecha);
        Fecha.setLayout(FechaLayout);
        FechaLayout.setHorizontalGroup(
            FechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FechaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbFecha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jlHora)
                .addContainerGap())
        );
        FechaLayout.setVerticalGroup(
            FechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FechaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(FechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbFecha)
                    .addComponent(jlHora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout FondoBlancoLayout = new javax.swing.GroupLayout(FondoBlanco);
        FondoBlanco.setLayout(FondoBlancoLayout);
        FondoBlancoLayout.setHorizontalGroup(
            FondoBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoBlancoLayout.createSequentialGroup()
                .addComponent(MenuOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FondoBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FondoBlancoLayout.createSequentialGroup()
                        .addGap(0, 501, Short.MAX_VALUE)
                        .addComponent(Fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Contorno, javax.swing.GroupLayout.DEFAULT_SIZE, 704, Short.MAX_VALUE))
                .addContainerGap())
        );
        FondoBlancoLayout.setVerticalGroup(
            FondoBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoBlancoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Contorno, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(MenuOpciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FondoBlanco, javax.swing.GroupLayout.DEFAULT_SIZE, 940, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FondoBlanco, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
        panelInicial();
    }//GEN-LAST:event_btnInicioActionPerformed

    private void btnEncuestasRecibidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEncuestasRecibidasActionPerformed
        panelPlantilas();
    }//GEN-LAST:event_btnEncuestasRecibidasActionPerformed

    //Metodo para Impletar un Panel dentro de Otro
    public void panelInicial(){
        PanelBienvenidaE pInicio = new PanelBienvenidaE();
            pInicio.setSize(700,500); //Colocamos el tamaño de nuestro Jpanel
            pInicio.setLocation(0,0);
            
            Contorno.removeAll();
            Contorno.add(pInicio,BorderLayout.CENTER);
            Contorno.revalidate();
            Contorno.repaint();
    }
    
    public void panelPlantilas(){
        /*
        CrearEncuestas pPlantillas = new CrearEncuestas();
            pPlantillas.setSize(700,500); //Colocamos el tamaño de nuestro Jpanel
            pPlantillas.setLocation(0,0);
            
            Contorno.removeAll();
            Contorno.add(pPlantillas,BorderLayout.CENTER);
            Contorno.revalidate();
            Contorno.repaint();
        */
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Contorno;
    private javax.swing.JPanel Fecha;
    private javax.swing.JPanel FondoBlanco;
    private javax.swing.JLabel Icon;
    private javax.swing.JPanel MenuOpciones;
    private javax.swing.JButton btnEncuestasRecibidas;
    private javax.swing.JButton btnEncuestasRespondidas;
    private javax.swing.JButton btnInicio;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jlHora;
    private javax.swing.JLabel lbFecha;
    // End of variables declaration//GEN-END:variables
}
