/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package T_Aplicacion;

import T_ArrayList.ListaEncuestadores;
import T_ArrayList.ListaParticipantes;
import T_CLASES.Encuestador;
import T_CLASES.Participante;
import T_CONEXION_BD.CRUDJavaE;
import T_CONEXION_BD.CRUDJavaP;
import java.sql.SQLException;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class LoginJDM extends javax.swing.JFrame {

    ListaEncuestadores T_listaEnc = new ListaEncuestadores(); 
    ListaParticipantes T_listaPart = new ListaParticipantes();
    private boolean isPasswordVisible = false;
    
    public LoginJDM() {
        initComponents();
        this.setTitle("JDM Surveys - Login");
        this.setSize(815, 540);
        this.setLocationRelativeTo(null);
        this.setResizable(false);  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg01 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jlbvariante = new javax.swing.JLabel();
        txtVariante = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnIniciarSesion = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnCrearcuenta = new javax.swing.JButton();
        rbEncuestador = new javax.swing.JRadioButton();
        rbParticipante = new javax.swing.JRadioButton();
        btnVision = new javax.swing.JButton();
        txtContraseña = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 500));

        jPanel1.setBackground(new java.awt.Color(102, 153, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(410, 500));
        jPanel1.setMinimumSize(new java.awt.Dimension(410, 500));

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel1.setText("TIPO DE USUARIO:");

        jlbvariante.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jlbvariante.setText("CODIGO:");

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel3.setText("PASSWORD :");

        btnIniciarSesion.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        btnIniciarSesion.setText("Iniciar sesión");
        btnIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarSesionActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("___________________________________________________");

        btnCrearcuenta.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        btnCrearcuenta.setText("Crear cuenta nueva");
        btnCrearcuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearcuentaActionPerformed(evt);
            }
        });

        bg01.add(rbEncuestador);
        rbEncuestador.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        rbEncuestador.setText("Encuestador");
        rbEncuestador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbEncuestadorActionPerformed(evt);
            }
        });

        bg01.add(rbParticipante);
        rbParticipante.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        rbParticipante.setText("Participante");
        rbParticipante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbParticipanteActionPerformed(evt);
            }
        });

        btnVision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnIniciarSesion, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                                    .addComponent(jLabel3)
                                    .addComponent(jlbvariante)
                                    .addComponent(txtVariante)
                                    .addComponent(txtContraseña))
                                .addGap(18, 18, 18)
                                .addComponent(btnVision, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rbEncuestador)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbParticipante))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(btnCrearcuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbEncuestador)
                    .addComponent(rbParticipante))
                .addGap(32, 32, 32)
                .addComponent(jlbvariante)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtVariante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnVision, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(btnIniciarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(btnCrearcuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 387, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearcuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearcuentaActionPerformed
        RegistroJDM T_nuevaV = new RegistroJDM();
            T_nuevaV.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_btnCrearcuentaActionPerformed

    private void rbEncuestadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbEncuestadorActionPerformed
        jlbvariante.setText("CODIGO:");
    }//GEN-LAST:event_rbEncuestadorActionPerformed

    private void rbParticipanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbParticipanteActionPerformed
        jlbvariante.setText("EMAIL:");
    }//GEN-LAST:event_rbParticipanteActionPerformed

    private void btnIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarSesionActionPerformed
        if(rbEncuestador.isSelected()){
            if(txtVariante.getText().length()==0){
                JOptionPane.showMessageDialog(this,"[x] Por Favor, Debe Ingresar su codigo");
                return;
            }
            
            String codigo = txtVariante.getText();

            // Verifica si el código tiene exactamente 9 dígitos (sin letra al inicio)
            Pattern validarNumeros = Pattern.compile("^[0-9]{9}$");
            Matcher validandoNumeros = validarNumeros.matcher(codigo);

            // Verifica si el código empieza con una letra pero tiene menos de 8 dígitos
            Pattern validarNumF = Pattern.compile("^[a-zA-ZáéíóúÁÉÍÓÚñÑ][0-9]{1,7}$");
            Matcher validandoNume = validarNumF.matcher(codigo);

            // Verifica si el código comienza con una letra y tiene exactamente 8 dígitos
            Pattern validarCodigo = Pattern.compile("^[a-zA-ZáéíóúÁÉÍÓÚñÑ][0-9]{8}$");
            Matcher validandoCodigo = validarCodigo.matcher(codigo);

            if (validandoCodigo.matches()) {
                // El código cumple con el formato correcto, continúa el flujo normal
            } else if (validandoNumeros.matches()) {
                JOptionPane.showMessageDialog(this, "[x] Falta la letra al inicio del código.");
                return; // Salir del método si falta la letra
            } else if (validandoNume.matches()) {
                JOptionPane.showMessageDialog(this, "[x] Faltan numeros en el código - Debe tener 8 nuemros después de la letra.");
                return; // Salir del método si faltan dígitos
            } else {
                JOptionPane.showMessageDialog(this, "[x] El código no cumple con el formato - Ejemplo: [Letra + 8 digitos].");
                return; // Salir del método si el formato es incorrecto
            }
            
            if(txtContraseña.getPassword().length==0){
                JOptionPane.showMessageDialog(this,"[x] Por Favor, Debe Ingresar su contraseña");
                return;
            }
            
            // Validate Encuestador login
            CRUDJavaE T_crudEncuestador = new CRUDJavaE();
            String contraseña = new String(txtContraseña.getPassword());

            Encuestador encuestadorLogueado = T_crudEncuestador.validarLoginEncuestador(codigo, contraseña);

            if (encuestadorLogueado != null) {
                SeccionEncuestadores T_se= new SeccionEncuestadores(T_listaEnc);
                    T_se.setVisible(true);
                    this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Código o contraseña incorrectos");
            }
            
            //Metodo para limpiar los controles
            limpiarControles();
        }else if(rbParticipante.isSelected()){
            if(txtVariante.getText().length()==0){
                JOptionPane.showMessageDialog(this,"[x] Por Favor, Debe Ingresar su Email");
                return;
            }
            
            if(txtContraseña.getPassword().length==0){
                JOptionPane.showMessageDialog(this,"[x] Por Favor, Debe Ingresar su contraseña");
                return;
            }
            
            //Validacion del Participante Login
            CRUDJavaP T_participantel = new CRUDJavaP();
            String email = txtVariante.getText();
            String contraseña = new String(txtContraseña.getPassword());
            
            Participante T_participanteLogueo = T_participantel.validarLoginPartipante(email, contraseña);
            
            if(T_participanteLogueo != null){
                SeccionParticipantes T_sp = new SeccionParticipantes(T_listaPart);
                    T_sp.setVisible(true);
                    this.dispose();
            }else{
                JOptionPane.showMessageDialog(this, "Email o contraseña incorrectos");
            }
            
            //Metodo para limpiar los controles
            limpiarControles();
        } else {
            JOptionPane.showMessageDialog(this, "Por favor, seleccione un tipo de usuario");
        }   
        
    }//GEN-LAST:event_btnIniciarSesionActionPerformed

    public void limpiarControles(){
        txtVariante.setText("");
        txtContraseña.setText("");
    }
    
    private void btnVisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisionActionPerformed
        if (isPasswordVisible) {

            txtContraseña.setEchoChar('•'); 
            isPasswordVisible = false; 
        } else {
            txtContraseña.setEchoChar((char) 0); 
            isPasswordVisible = true; 
        }
    }//GEN-LAST:event_btnVisionActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bg01;
    private javax.swing.JButton btnCrearcuenta;
    private javax.swing.JButton btnIniciarSesion;
    private javax.swing.JButton btnVision;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jlbvariante;
    private javax.swing.JRadioButton rbEncuestador;
    private javax.swing.JRadioButton rbParticipante;
    private javax.swing.JPasswordField txtContraseña;
    private javax.swing.JTextField txtVariante;
    // End of variables declaration//GEN-END:variables
}
