/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package T_Aplicacion;

/**
 *
 * @author Usuario
 */
public class P12_InfoPlataforma extends javax.swing.JPanel {

    /**
     * Creates new form P12_InfoPlataforma
     */
    public P12_InfoPlataforma() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(300, 300));
        setMinimumSize(new java.awt.Dimension(300, 300));
        setPreferredSize(new java.awt.Dimension(300, 300));

        jLabel1.setText("<html><center>JDM Surveys es una plataforma de encuestas diseñada para facilitar la recolección de datos de manera eficiente y precisa. Ofrece una interfaz intuitiva que permite crear, distribuir y analizar encuestas con facilidad. Con diversas herramientas de personalización y análisis de resultados, JDM Surveys es ideal para investigaciones académicas, estudios de mercado y recopilación de opiniones de los clientes. La plataforma también proporciona reportes detallados y visualizaciones gráficas para interpretar los datos de manera clara y efectiva.");
        jLabel1.setMaximumSize(new java.awt.Dimension(288, 288));
        jLabel1.setMinimumSize(new java.awt.Dimension(288, 288));
        jLabel1.setPreferredSize(new java.awt.Dimension(288, 288));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
